# This is a basic workflow to help you get started with Actions

name: Git-Finder-Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    name: Initial Setup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x

      # Runs a single command using the runners shell
      - name: Install Yarn
        run: npm install -g yarn typescript

      - name: Install Dependencies
        run: yarn install

      - name: Transpile Code
        run: tsc

      - name: Execute Tests
        run: yarn test

      # - name: Build Initial Artifact
      #   run: yarn pack

  build-deb:
    name: Build Debian Binary
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x

      # Runs a single command using the runners shell
      - name: Install Yarn
        run: npm install -g yarn typescript

      - name: Install Dependencies
        run: yarn install

      - name: Transpile Code
        run: tsc

      - name: Build Binary
        run: yarn pack:deb

  build-win:
    name: Build Windows Binary
    runs-on: windows-latest
    needs: setup
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x

      # Runs a single command using the runners shell
      - name: Install Yarn
        run: npm install -g yarn typescript

      - name: Install Dependencies
        run: yarn install

      - name: Transpile Code
        run: tsc

      - name: Build Binary
        run: yarn pack:win

  build-mac:
    name: Build macOS Binary
    runs-on: macos-latest
    needs: setup
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x

      # Runs a single command using the runners shell
      - name: Install Yarn
        run: npm install -g yarn typescript

      - name: Install Dependencies
        run: yarn install

      - name: Transpile Code
        run: tsc

      - name: Build Binary
        run: yarn pack:mac
